// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	predictor "sod/internal/predictor"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DataPoint is an autogenerated mock type for the DataPoint type
type DataPoint struct {
	mock.Mock
}

// Point provides a mock function with given fields:
func (_m *DataPoint) Point() predictor.Point {
	ret := _m.Called()

	var r0 predictor.Point
	if rf, ok := ret.Get(0).(func() predictor.Point); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(predictor.Point)
		}
	}

	return r0
}

// Time provides a mock function with given fields:
func (_m *DataPoint) Time() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}
