// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Point is an autogenerated mock type for the Point type
type Point struct {
	mock.Mock
}

// Dim provides a mock function with given fields: idx
func (_m *Point) Dim(idx int) float64 {
	ret := _m.Called(idx)

	var r0 float64
	if rf, ok := ret.Get(0).(func(int) float64); ok {
		r0 = rf(idx)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// Dimensions provides a mock function with given fields:
func (_m *Point) Dimensions() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Points provides a mock function with given fields:
func (_m *Point) Points() []float64 {
	ret := _m.Called()

	var r0 []float64
	if rf, ok := ret.Get(0).(func() []float64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	return r0
}
